// angular-app/src/app/components/menu/menu.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent implements OnInit {
  items = [
    {
      label: 'Home', 
      icon: 'pi pi-fw pi-home', 
      path: '/', 
      command: (event:any) => {
        this.onTabChange(event);
      }
    },
    {
      label: 'Blog', 
      icon: 'pi pi-fw pi-file', 
      path: 'blog',
      command: (event: any) => {
        this.onTabChange(event);
      }
    }
  ]

  @Input() index: number = 0

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  onTabChange(event: any): void{
    console.log('event', event)
    this.router.navigate([event.item.path])

  }

}

<p-tabMenu [model]="items" [activeItem]="items[index]">
    <!-- <ng-template pTemplate="item" let-item let-i="index">
        <span (click)="onTabChange(item.path);">{{item.label}}</span>
    </ng-template> -->
</p-tabMenu>

// react-app/src/components/Menu.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { TabMenu } from 'primereact/tabmenu';

const Menu: React.FC<{active: number}> = ({active=0}) => {

  const navigate = useNavigate();

  const onTabChange = (ev: any) => {
    navigate(ev.path)
  }

  const items = [
    {label: 'Home', icon: 'pi pi-fw pi-home', path: '/'},
    {label: 'Blog', icon: 'pi pi-fw pi-file', path: '/blog'}
  ]


  return (
    <div>
      <TabMenu model={items} activeIndex={active} onTabChange={(e) => onTabChange(e.value)}/>
    </div>
  )
}

export default Menu
