// react-app/src/pages/Blog.tsx
import React from 'react';
import { getBlogPosts } from '../services/api';
import { Noticia } from "../models/Noticia.model";
import { Card } from 'primereact/card';
import Menu from '../components/Menu';
import { ProgressSpinner } from 'primereact/progressspinner';

const Blog: React.FC = () => {

  const [posts, setPosts] = React.useState<Noticia[]>([])
  const [loading, setLoading] = React.useState<boolean>(false);

  const getBlogData = () => {
    setLoading(true)
    getBlogPosts().then(res => {
      setPosts(res.data)
      setLoading(false)
    })
  }

  const footer = (url: string)=> (<a href={url} target="_blank" rel="noreferrer">Ver mais</a>)
  const header = (url: string) => <img alt="Card" src={url} />

  React.useEffect(()=>{
    getBlogData()
  }, [])

  return (
    <div style={{marginTop: '3rem', minHeight: '30rem'}}>
      <Menu active={1}/>
      {loading ? 
        <ProgressSpinner /> :
        posts.map((post: Noticia) => (
          <Card 
            style={{minWidth: '20rem', width: '40%',margin: ' 1rem auto'}}
            header={()=>header(post.imageUrl)}
            title={post.title} 
            key={post.id}
            footer={()=>footer(post.url)}
          >
              {post.summary}
          </Card>
        ))
      }
      
    </div>
  )
}

export default Blog

// angular-app/src/app/pages/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';
import { Noticia } from 'src/app/models/Noticia.model';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.scss']
})
export class BlogComponent implements OnInit {
  carregando: boolean = false
  posts: Noticia[] = []

  constructor(private apiService: ApiService) { }

  ngOnInit(): void {
    this.carregando = true
    this.apiService.getBlogPosts().subscribe((res: any)=>{
      this.posts = res
      this.carregando = false
    })
  }

}

<div>
    <app-menu [index]="1" ></app-menu>
    <div class="spinner">
        <p-progressSpinner *ngIf="carregando"></p-progressSpinner>
    </div>
    <div class="posts">
        <div *ngFor="let post of posts">
            <p-card 
                [style]="{'min-width': '25rem', 'width':'40%','margin': '2em auto'}"
                [header]="post.title" 
                styleClass="p-card-shadow"
            >
                <ng-template pTemplate="header">
                    <img alt="Card" [src]="post.imageUrl">
                </ng-template>
                <ng-template pTemplate="content">
                    {{post.summary}}
                </ng-template>
                <ng-template pTemplate="footer">
                    <a target="_blank" [href]="post.url">Ver mais</a>
                </ng-template>
            </p-card>
        </div>
    </div>
</div>
